apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

labels:
- pairs:
    app: scheduling-api
    component: api
    service: scheduling

images:
- name: ghcr.io/luuklabs/kdvmanager/scheduling.api
  newName: ghcr.io/luuklabs/kdvmanager/scheduling.api
  newTag: linux-7166f2a
- name: ghcr.io/luuklabs/kdvmanager/scheduling.migrator
  newName: ghcr.io/luuklabs/kdvmanager/scheduling.migrator
  newTag: linux-7166f2a
