apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

labels:
- pairs:
    app: crm-api
    component: api
    service: crm

images:
- name: ghcr.io/luuklabs/kdvmanager/crm.api
  newName: ghcr.io/luuklabs/kdvmanager/crm.api
  newTag: linux-711509c
- name: ghcr.io/luuklabs/kdvmanager/crm.migrator
  newName: ghcr.io/luuklabs/kdvmanager/crm.migrator
  newTag: linux-711509c
