---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: kdvmanager-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBM33S1fdB6WSjyJXiKJ+wuy13VOSnQnbmEGYDnhPa7OkWYsaJ72ibfqFymUfuybkR73t+qv849ATI8v+QSG+1rpRTP9PcbimR/NGi5BTB8rkOh/XLsum9EOibkSB9AGsBleNq3KhvsiVlqS2L9MqdjjxnJT3bsqTQRDumHq+K1v2K56xnEj3CXLOSL1JT4Tp7Bp4Q7UHsTPriwT0C74tzSUlBqYB6goU0U41GV5qxNXHkjLPK9pnBiItApbXt46rEE706MQdP39vVTwlxQtNYbT5MI/LbL2Ihm4mUg9FLRaNQpE3+SgPySXtQQcIuL8OheTo85zWaBQn+m/RTkXYqZ8rL8n8RV8unUY1C92G/HCb2R8qjoRYOmQx6l104SUVDFrmNw+EsNV0s2H2IleCYB+JLgJUf+SpQxioLTYYqFFMZ8YEck1Fn10A2WJbGhoLd0JOsG4/e+IXMQk6YrICm3E892k0Rbc1wkTlH3PT2H+FtJPZ0GlM2/NDPBY8xmsCSbZZfXf/f9FdEQ+/f5oo55mjKLbvvCVWLwsM5LQcgTcxk8Kze9O2B/dTZ0HcKzAwKsxMuRZ4QCSxvaIHpeziPKWiYtApRlta6VqsAdjc4VP6+HNzfWzBn3WpiQJRSiM8JGZ8PdK4EPo0ecXeX3kddqlxc7A/AUv+WsbDl+wR8XiaptUsnS2rqYOj9H5rYwgVqUqpS3PDhwf8HGlUom4r8hPQVz4hUFBIvzi6e4vGU6auMODmVA6KN9hCDo+eP2mBM1ny9CM01IZhTwFB2lxzZ0MO/nAUERoadT1LXQuX/wgO57mUULrc+e10l5HyBDJBymXF9B9f3jUGVWzgr75Vho7urQxJ7Q/gswDtBBoTsaH4BdN9MuJvFshQPFsYU2xqgQsn8yGJj3M56CqEO/6beKBg0PzWwtiy3j7bk=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: kdvmanager-prod
    type: kubernetes.io/dockerconfigjson
